config/routes.rb
Rails.application.routes.draw do
  root 'lists#index'
  resources :lists do
    collection do
      post :confirm
      get :new_redirect
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/list.rb
class List < ApplicationRecord
  validates :content, presence: true
  validates :content, length: {maximum: 140}
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/lists_controller.rb
class ListsController < ApplicationController
  before_action :set_list, only: [:show,:destroy,:edit]
  
  def index
    @lists = List.all
    @list = List.new
  end

  def new
    @list = List.new
  end

  def new_redirect
    @list = List.new(content: params[:content])
  end

  def create
    @list = List.new(list_params)
    if @list.save
      redirect_to lists_path, notice:"投稿しました。"
    else
      render"new"
    end
  end

  def show
  end

  def confirm
    @list = List.new(list_params)
    render"new" if @list.invalid?
  end

  def destroy
    @list.destroy
    redirect_to lists_path, notice:"削除しました。"
  end

  def edit
  end

  def update
    @list = List.find(params[:id])
    if @list.update(list_params)
      redirect_to lists_path, notice:"編集しました。"
    else
      render "edit"
    end
  end

  private

  def list_params
    params.require(:list).permit(:content)
  end

  def set_list
    @list = List.find_by(id: params[:id])
  end
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Tclone</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    
  </head>

  <body>
    <div class="container">
    <header class = "header">
      <h1>Tclone</h1>
    </header>
    <%= yield %>
    <footer class = "footer">
      <h1>Copyright © 2018 DIVE INC All RIGHTS RESERVED.</h1>
    </footer>
    </div>
  </body>
</html>

app/views/lists/confirm.html.erb
<h3>以下の内容で、送信する。</h3>
<br>
<%= form_with(model: @list, url: lists_path, local: true) do |form| %>
  <%= form.hidden_field :content %>
  <br>
  <p><%= @list.content %></p>
  <br>
  <span  class= "btnlike"><%= form.submit  "登録する" %></span>
  <%= link_to "戻る", new_redirect_lists_path(content: @list.content), class: "btnlike" %>
<% end %>

app/views/lists/edit.html.erb
<%= form_with(model: @list, url: list_path, local: true) do |form| %>
  <% if @list.errors.any? %>
    <div id="error_explanation">
      <h2><%= @list.errors.count %>件のエラーがあります。</h2>
      <ul>
      <br>
      <% @list.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <br>
  <div class="content">
    <%= form.label :"内容" %>
    <%= form.text_area :content, size: "100x10" %>
  </div>
  <span  class= "btnlike"><%= form.submit name="保存する"%></span>
  <%= link_to '戻る', :back, class: "btnlike" %>
<% end %>

app/views/lists/index.html.erb
<%= form_with(model: @list, url: confirm_lists_path, local: true) do |form| %>
  <% if @list.errors.any? %>
    <div id="error_explanation">
      <h2><%= @list.errors.count %>件のエラーがあります。</h2>
      <ul>

      <% @list.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="content">
    <%= form.label :"入力欄" %>
    <br>
    <%= form.text_area :content, size: "100x10", placeholder: "140文字以内で入力してください" %>
  </div>
 
   <span class = "button"><%= form.submit name="投稿する" %></span>
<% end %>

<p class = "notice"><%= notice %></p>

<div class="table_round">
<table border=1>
  <tr>
    <th>投稿一覧</th>
  </tr>
  <% @lists.each do |list| %>
  <tr>
    <td><%= link_to list.content,list_path(list.id) %></td>
  </tr>
  <% end %>
</table>
</div>

app/views/lists/new.html.erb
<%= form_with(model: @list, url: confirm_lists_path, local: true) do |form| %>
  <% if @list.errors.any? %>
    <div id="error_explanation">
      <h2><%= @list.errors.count %>件のエラーがあります。</h2>
      <ul>

      <% @list.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <br>
  <div class="content">
    <%= form.label :"内容" %>
    <%= form.text_area :content, size: "100x10" %>
  </div>
  <br>
  <span class = "button"><%= form.submit name="投稿する" %></span>
<% end %>
<br>
<%= link_to "一覧に戻る", lists_path, class: "btnlike" %>

app/views/lists/new_redirect.html.erb
<%= form_with(model: @list, url: confirm_lists_path, local: true) do |form| %>
  <div class="content">
    <%= form.label :"内容" %>
    <%= form.text_area :content , size: "100x10"%>
  </div>
  <br>
  <span class = "button"><%= form.submit name="投稿する"%></span>
<% end %>
<br>
<%= link_to "一覧画面", lists_path, class: "btnlike" %>

app/views/lists/show.html.erb
<h1>詳細画面 </h1>
<br>
<p>内容：<%= @list.content %></p>
<br>
<%= link_to '編集', edit_list_path, class: "btnlike" %>
<%= button_to '削除', list_path, method: :delete, class: "btnlike" %>
<%= link_to '投稿一覧', lists_path, class: "btnlike" %>